const courses = [
  {
    id: 1,
    title: "Zero to Hero with Nodejs",
    thumbnail: "./../assets/images/courses/course-4.jpg",
    author: "Mohi Uddin",
    authorImg: "./../assets/images/author/author.jpg",
    courseFee: "Free",
    totalEnroll: "260",
    reviews: "3",
  },
  {
    id: 2,
    title: "Introduction LearnPress- LMS plugin",
    thumbnail: "./../assets/images/courses/course-2.jpg",
    author: "Mohi Uddin",
    authorImg: "./../assets/images/author/author.jpg",
    courseFee: "Free",
    totalEnroll: "280",
    reviews: "0",
  },
  {
    id: 3,
    title: "Learn Python Interactive Python Tutorial",
    thumbnail: "./../assets/images/courses/course-3.jpg",
    author: "Mohi Uddin",
    authorImg: "./../assets/images/author/author.jpg",
    courseFee: "$49.00",
    totalEnroll: "560",
    reviews: "30",
  },
  {
    id: 4,
    title: "Complete Photography Crash Course",
    thumbnail: "./../assets/images/courses/course-4.jpg",
    author: "Mohi Uddin",
    authorImg: "./../assets/images/author/author.jpg",
    courseFee: "$39.00",
    totalEnroll: "40",
    reviews: "2",
  },
  {
    id: 5,
    title: "Learn Complete Android Mobile Application Development",
    thumbnail: "./../assets/images/courses/course-5.jpg",
    author: "Mohi Uddin",
    authorImg: "./../assets/images/author/author.jpg",
    courseFee: "$79.00",
    totalEnroll: "250",
    reviews: "30",
  },
  {
    id: 6,
    title: "Learn Complete Frontend Development",
    thumbnail: "./../assets/images/courses/course-6.jpg",
    author: "Mohi Uddin",
    authorImg: "./../assets/images/author/author.jpg",
    courseFee: "$89.00",
    totalEnroll: "160",
    reviews: "33",
  },
  {
    id: 7,
    title: "Complete Webdesign HTML/CSS Essential in 4 Hours",
    thumbnail: "./../assets/images/courses/course-7.jpg",
    author: "Mohi Uddin",
    authorImg: "./../assets/images/author/author.jpg",
    courseFee: "Free",
    totalEnroll: "30",
    reviews: "10",
  },
  {
    id: 8,
    title: "Become a PHP Master and Make Money Fast",
    thumbnail: "./../assets/images/courses/course-8.jpg",
    author: "Mohi Uddin",
    authorImg: "./../assets/images/author/author.jpg",
    courseFee: "$59.00",
    totalEnroll: "79",
    reviews: "0",
  },
  {
    id: 9,
    title: "Become a Full-Stack Developer",
    thumbnail: "./../assets/images/courses/course-9.jpg",
    author: "Mohi Uddin",
    authorImg: "./../assets/images/author/author.jpg",
    courseFee: "$129.00",
    totalEnroll: "260",
    reviews: "3",
  },
  {
    id: 10,
    title: "Complete Guide of Javascript Developer",
    thumbnail: "./../assets/images/courses/course-10.jpg",
    author: "Mohi Uddin",
    authorImg: "./../assets/images/author/author.jpg",
    courseFee: "Free",
    totalEnroll: "260",
    reviews: "3",
  },
];
